### ISSUE TITLE
一个size的bug

### ISSUE THREAD

**Issue by chenweibo** [gera2ld/qrcanvas#10]
demo里面用cellSize 用作调整码的大小，  改用size后  改变码的大小 logo 不会居中。 改回用cellSize 可以的 没这个bug

**Comment by gera2ld** [comment]
我试了一下没问题啊，给个重现？

**Comment by chenweibo** [comment]
@gera2ld  http://jsrun.net/jThKp/detail  
我在我的上面好几个断点的尺寸拖的时候就会这样 我稍微选了一个尺寸

**Comment by chenweibo** [comment]
我之前写的demo 是基于webpack的 后面在稍微大一点尺寸拖拉也出现这个问题。 我就稍微用了你的这个图 在 104这个点就出现了这个不居中 我只好换回cellSize  就都没这个问题

**Comment by gera2ld** [comment]
fixed in d895210
