### ISSUE TITLE
Consult about the QR code version number corresponding to the QR code generated by the current QR code library

### ISSUE THREAD

**Issue by bobcao0320** [gera2ld/qrcanvas#16]
Hello:
        Thank you for your contribution to the qrcode generation library. If you have a question, there is a parameter typeNumber that specifies the QR code version in the input parameters of the generation library.

const DEFAULTS: QRCanvasOptions = {
  background: 'white',
  foreground: 'black',
  **typeNumber: 0,**
  correctLevel: 'L',
  data: '',
  padding: 0,
  resize: true,
};
What is the final output value of this parameter after generating the QR code?

**Comment by gera2ld** [comment]
There is no way to get the final `typeNumber` now. Can you describe why this result is needed?

**Comment by bobcao0320** [comment]
Because we have encountered the problem that the QR code of the business cannot be recognized by the scanning gun, we can recognize the QR code after reducing the fault tolerance rate, so I want to study and explore the QR code fault tolerance rate, QR code version The relationship between the information and the accuracy of the code scanner, thank you. 


------------------&nbsp;Original&nbsp;------------------
