### ISSUE TITLE
[Question] Apply additional style to canvas

### ISSUE THREAD

**Issue by chenwoniu** [gera2ld/qrcanvas#18]
If only options.size is specified without or not integer multiples of cellSize , the QrCode image will be blurred. I wonder if it's caused by scalling the image by canvas.drawImages(). So let's do like: 

let definedCellSize = options.cellSize;  //nullable
options.cellSize = definedCellSize || 1;
image.onload = () => {
  const canvas = qrcanvas.qrcanvas(options);
  canvas.setAttribue("style", "width: " + options.size + "px; height: " + options.size + "px;");
  container.appendChild(canvas);
};

Runs well！
Could you please resolve it within your package?

**Comment by gera2ld** [comment]
This package has nothing to do with CSS, you can apply CSS by yourself or reuse an existed canvas, for example:

```html
<!-- html -->
<canvas style="width: 300px; height: 300px">
```

```js
// js
const canvas = findThatCanvas();
qrcanvas.qrcanvas({
  canvas,
  cellSize: 2,
});
```
