### ISSUE TITLE
请添加上dist目录

### ISSUE THREAD

**Issue by jumplee** [gera2ld/qrcanvas#2]
没有下载的地方。需要自己build。希望更方便一些

**Comment by gera2ld** [comment]
请使用`npm install qrcanvas`安装，或者从<https://unpkg.com/qrcanvas>获取最新版代码。

**Comment by jumplee** [comment]
建议将https://unpkg.com/qrcanvas放到readme中。

**Comment by jumplee** [comment]
建议将  https://unpkg.com/qrcanvas   放到readme中
