### ISSUE TITLE
添加logo的方法？

### ISSUE THREAD

**Issue by artdong** [gera2ld/qrcanvas#3]
var canvas = qrcanvas({
      data: 'hello, world',
      cellSize: 8,
      size: 250,
      typeNumber: 4,
      correctLevel: 'H',
      foreground: 'blue',
      background: 'yellow',
      logo: {image: '../assets/img/me.background.jpg'}
    });
这样加logo不对？
https://gera2ld.github.io/qrcanvas/ 你这个demo地址能否告知下？

**Comment by gera2ld** [comment]
image必须是一个Image元素，你需要自己去加载图片：
```js
var image = new Image();
image.src = '../assets/img/me.background.jpg';
image.onload = function () {
  var canvas = ...
};
```

demo源码在 https://github.com/gera2ld/qrcanvas/tree/master/src/demo
