### ISSUE TITLE
Node version fails to scan

### ISSUE THREAD

**Issue by dabruhce** [gera2ld/qrcanvas#5]
I was looking to see if I could wrap this into a lambda function using the node version.  An image does appear, but it seems like the qrcode image result can't be read.  It does produce a qr code looking image.

Tested w/ 
windows - node@6.11.1
docker image lambci/lambda:nodejs6.10

Haven't had a chance to verify similar results on mac.

using canvas w/ fs write & toDataUrl produced the same image which could not be scanned. 

````text
e.g.
canvas.pngStream().pipe(fs.createWriteStream('qrcode.png'));
let dataUrl = canvas.toDataURL('image/png');
````

## returned image
````text

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKgAAACoCAYAAAB0S6W0AAAABmJLR0QA/wD/AP+gvaeTAAAC/0lEQVR4nO3dQY6jMBBAURj1/a+cucCovbA89QnvrZtAOl9elAzc13V9ri/2+fz+9e77/k9X8m+r61uZvv7T/kxfAPxGoKQJlDSBkiZQ0gRKmkBJ+1n9we6c7rTTc8D691+pX//q97OCkiZQ0gRKmkBJEyhpAiVNoKQt56ArT59D7u4XPX38afXfzwpKmkBJEyhpAiVNoKQJlDSBkrY9B3263Tng6eOn56TTrKCkCZQ0gZImUNIESppASRMoaa+fg07PGb/9+Z67rKCkCZQ0gZImUNIESppASRMoadtz0Ok54mnffl/89PlXrKCkCZQ0gZImUNIESppASRMoacs56LfvV5yec56ekz7997OCkiZQ0gRKmkBJEyhpAiVNoKTdn/qGwMN254TTc85vZwUlTaCkCZQ0gZImUNIESppASTu+H3R3Tnja6eub/v6n95Oe/n5WUNIESppASRMoaQIlTaCkCZS05Ry0vl9x+vpOz0mnTe93tYKSJlDSBEqaQEkTKGkCJU2gpP3U9yOuTD+f8+3H71qd3wpKmkBJEyhpAiVNoKQJlDSBkvZTfw/P9H7J6fv2d89fv/7V72sFJU2gpAmUNIGSJlDSBEqaQEnb3g86/fzL0/sZp5+vefrzV8dP3/dvBSVNoKQJlDSBkiZQ0gRKmkBJe/374uum55DT991bQUkTKGkCJU2gpAmUNIGSJlDSjj8fdNr08zGnn785bff/bwUlTaCkCZQ0gZImUNIESppASXv8++Kn57jT559+LsFpVlDSBEqaQEkTKGkCJU2gpAmUtOUcdOXt70ma3i96+viV3fO7L55HEyhpAiVNoKQJlDSBkiZQ0rbnoE93eo55+vy76s8NsIKSJlDSBEqaQEkTKGkCJU2gpL1+Dvr0981Psx+UVxMoaQIlTaCkCZQ0gZImUNK256DT+xlPm75vfffznz7ntYKSJlDSBEqaQEkTKGkCJU2gpN3XdX31ILO+H3P6vvSV6fv+raCkCZQ0gZImUNIESppASRMoaX8Bw877YrWRC0kAAAAASUVORK5CYII=

````

**Comment by gera2ld** [comment]
The image you provided can be scanned easily for me:

![image](https://user-images.githubusercontent.com/3139113/39166899-c775f8f2-47be-11e8-8c23-bfbe6785a48c.png)

Also tried with online decoder here: https://zxing.org/w/decode.jspx

**Comment by dabruhce** [comment]
Thanks. You are right. I believe the issue is that the qrcode was getting washed out on my screen w/ a black background since it doesn't have a built-in border. Which isn't a problem when you embed the qr on another element.

![image](https://user-images.githubusercontent.com/4344301/39194260-e8f2ad52-47a2-11e8-9039-9c61f5ada84e.png)
