### ISSUE TITLE
如何把canvas转成图片？

### ISSUE THREAD

**Issue by KaivOU** [gera2ld/qrcanvas#8]
如何把canvas转成图片？
使用了
      var img = document.getElementById("save_img");
var canvas = document.getElementById("canvas");
    var tempSrc = canvas.toDataURL("image/png");
    img.src=tempSrc;
发现手机上是不行的，微信调试工具上行

**Comment by gera2ld** [comment]
因为跨域了？这跟这个库没啥关系吧。。
