### ISSUE TITLE
换到了你的新库试了下用css 控制内边距发现 另存没效果。

### ISSUE THREAD

**Issue by chenweibo** [gera2ld/qrcanvas#9]
我看了nmp 上一些包。 比如node-qrcode  或者jqury-qrocode 都有画布和这个码的内边距调整。 我需要怎么操作呢 大佬 。

**Comment by chenweibo** [comment]
实现下面这个安静区域 如下图
![2018-10-27 3 56 09](https://user-images.githubusercontent.com/19586007/47601298-ff20e080-da00-11e8-9313-beb5b1a6f1d1.png)

**Comment by gera2ld** [comment]
目前没有这个功能，你在什么场景下使用？为啥不能直接用css控制？

**Comment by chenweibo** [comment]
@gera2ld 不知道为什么不能用css 控制。  css控制在chrome里面调试是可以的 另存下来就没了。后面我通过新建一个空白canvas 两个合并 得到了这个安静区域。这样另存后就不影响了。

**Comment by gera2ld** [comment]
这个可以有，我有空加一下，也欢迎PR

**Comment by gera2ld** [comment]
Example: https://gera2ld.github.io/qrcanvas/examples/#padding
